from . import Inherit_Template
from . import Inherit_res
from . import Inherit_sale_order
from . import Inherit_Project_Project
from . import Inherit_crm
from . import Inherit_analytic_account
from . import Inherit_Project_Task
from . import Inherit_hr_employee
from . import Inherit_Account_Move
from . import Inherit_purchase_order
from . import Inherit_Hr_Expense
from . import Inherit_Expenses_Sheet